version: '3.8'

services:
  db:
    image: postgres:15
    container_name: springboot_postgres
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
